version: '3'
services:
  app:
    container_name: api
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
    env_file:
      - .env
    depends_on:
      - db
      
  db:
    container_name: mongo-db
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
      